config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/valeurs', to: 'pages#valeurs', as: 'valeurs'

  # Contact
  get '/contact', to: 'messages#new', as: 'new_message'
  post '/contact', to: 'messages#create', as: 'create_message'

  resources :articles, only: [:index, :show]
  resources :contacts, only: [:create]

  get '/admin', to: 'pages#admin', as: 'admin'
  namespace :admin do
    resources :articles
  end

  # Youtube to Trix
  resources :youtube, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  has_one_attached :photo

  validates :title, presence: true
  validates :photo, presence: true
  validates :content, presence: true

  scope :ordered_by_creation_reverse, -> { order(:created_at).reverse_order }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_content,
    against: [ :title, :content ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    paginates_per 6
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
      format: { with: /\A[^@\s]+@[^@\s]+\z/,
              message: "L'adresse email n'est pas valide" },
      presence: true
  validates_uniqueness_of :email, message: "Vous êtes déjà inscrit ! :)"
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :first_name, :last_name, :email, :body, :subject

  validates_presence_of :last_name
  validates_presence_of :first_name
  validates_presence_of :email
  validates_presence_of :body
  validates_presence_of :subject
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable,
          # :registerable,
          # :recoverable,
          :rememberable,
          :validatable
end

app/models/youtube.rb
class Youtube
  include ActiveModel::Model
  include ActiveModel::Attributes
  include GlobalID::Identification
  include ActionText::Attachable

  attribute :id

  def self.find(id)
    new(id: id)
  end

  def thumbnail_url
    "http://i3.ytimg.com/vi/#{id}/maxresdefault.jpg"
  end

  def to_trix_content_attachment_partial_path
    "youtubes/thumbnail"
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :get_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all.ordered_by_creation_reverse.page params[:page]
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :photo, :displayed)
  end

  def get_article
    @article = Article.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # For metatags
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query]
      @articles = Article.where(displayed: true).search_by_title_and_content(params[:query]).ordered_by_creation_reverse.page params[:page]
    else
      @articles = Article.where(displayed: true).ordered_by_creation_reverse.page params[:page]
    end
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      SendinblueContactCreator.call(@contact.email)
      flash[:notice] = "Vous êtes bien inscrit, merci !"
      redirect_back(fallback_location: root_path)
    else
      @contact.errors.messages[:email].each { |message| flash[:alert] = message }
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to root_path, notice: "Nous avons bien reçu votre message, merci !"
    else
      render :new
    end
  end

  protected

  def message_params
    params.require(:message).permit(:first_name, :last_name, :subject, :email, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :valeurs, :show_example]

  def admin
  end

  def home
    @articles = Article.where(displayed: true).limit(3).ordered_by_creation_reverse
  end

  def valeurs
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  def show
    @youtube = Youtube.new(id: params[:id])
    render json: {
      sgid: @youtube.attachable_sgid,
      content: render_to_string(partial: "youtubes/thumbnail", locals: { youtube: @youtube }, formats: [:html])
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/articles/edit.html.erb
<div class="container min-height-calc adjusted-padding">
  <div class="mb-3">
    <%= link_to '< Retour à la liste des articles', admin_articles_path, class: "admin-back-link" %>
  </div>
  <h1 class="text-green">Éditer votre Article</h1>

  <%= simple_form_for @article, url: admin_article_path(@article) do |f| %>
    <%= f.input :title,
                label: 'Titre'
    %>
    <%= f.input :photo, as: :file %>
    <%= f.input :content,
      as: :rich_text_area,
      label: 'Contenu'
    %>
    <div class="custom-control custom-switch mb-2">
      <%= f.check_box :displayed,
                as: :boolean,
                class: "custom-control-input",
                id: "customSwitch1" %>
      <label class="custom-control-label" for="customSwitch1">Afficher l'article ?</label>
    </div>

    <div class="w-100 d-flex justify-content-between">
      <%= f.submit "Éditer l'article", class: "btn btn-primary" %>
      <%= link_to admin_article_path(@article), method: :delete, data: { confirm: "T'es sûr ou c'est Clément qui est bourré ?" }  do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/articles/index.html.erb
<div class="container-lg min-height-calc adjusted-padding">
  <div class="mb-3">
    <%= link_to '< Retour au menu admin', admin_path, class: "admin-back-link" %>
  </div>
  <h1 class="w-100 text-center text-green">Liste des articles</h1>

  <div class="w-100 d-flex justify-content-center my-4">
    <%= link_to 'Ajouter un article', new_admin_article_path, class: "btn btn-primary" %>
  </div>

  <div class="w-100 d-flex justify-content-center">
    <%= paginate @articles %>
  </div>
  <div class="row m-auto">
    <% @articles.each do |article| %>
      <div class="col-4 d-flex justify-content-center mb-4">
        <div class="card admin-article-card" style="width: 18rem;">
          <%= cl_image_tag article.photo.key, class: "card-img-top" %>
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-center">
              <h5 class="text-green card-title text-clamp-2"><%= article.title %></h5>
            </div>
            <p class="primary-bold mb-2">Publié le : <%= article.created_at.strftime("%d/%m/%Y") %></p>
            <p class="card-text text-clamp-6"><%= article.content %></p>
          </div>
          <div class="admin-post-buttons">
            <%= !article.displayed ? "<i class='fas fa-eye-slash' style='color: red; margin: 10px;'></i>".html_safe : "<span></span>".html_safe %>
            <div>
              <%= link_to edit_admin_article_path(article) do %>
                <i class="admin-icon fas fa-pencil-alt" data-toggle="tooltip" data-placement="top" title="Éditer l'article"></i>
              <% end %>
              <%= link_to admin_article_path(article) do %>
                <i class="admin-icon fas fa-eye" data-toggle="tooltip" data-placement="top" title="Voir l'article"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="w-100 d-flex justify-content-center">
    <%= paginate @articles %>
  </div>
</div>

app/views/admin/articles/new.html.erb
<div class="container min-height-calc adjusted-padding">
  <div class="mb-3">
    <%= link_to '< Retour à la liste des articles', admin_articles_path, class: "admin-back-link" %>
  </div>
  <h1 class="text-green">Ajouter un Article</h1>

  <%= simple_form_for @article, url: admin_articles_path do |f| %>
    <%= f.input :title,
                label: 'Titre',
                placeholder: 'Votre titre ici'
    %>
    <%= f.input :photo, as: :file %>
    <%= f.input :content,
      as: :rich_text_area,
      label: 'Contenu',
      placeholder: 'Le contenu ici...'
    %>
    <div class="custom-control custom-switch mb-3">
      <%= f.check_box :displayed,
                as: :boolean,
                class: "custom-control-input",
                id: "customSwitch1" %>
      <label class="custom-control-label" for="customSwitch1">Afficher l'article ?</label>
    </div>
    <%# Ajouter le style à l'input pour qu'il soit scrollable =>  overflow-y: auto; %>
    <%= f.submit "Publier l'article", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/articles/show.html.erb
<div class="container-lg adjusted-padding">
  <div class="mb-3">
    <%= link_to '< Retour à la liste des articles', admin_articles_path, class: "admin-back-link" %>
  </div>
  <div class="d-flex flex-column align-items-center">
      <%= cl_image_tag @article.photo.key, style: "max-width: 80%; max-height: 400px;", class: "mb-4" %>

      <h1 class="text-green mb-4"><%= @article.title %></h1>
      <p class="primary-bold mb-4">Publié le : <%= @article.created_at.strftime("%d/%m/%Y") %></p>

      <p><%= @article.content %></p>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container-lg min-height-calc">

  <div class="row adjusted-padding">
    <%# Display cards %>
    <div class="col-12 col-md-8">
      <h1 class="text-green mb-4">Nos articles</h1>

      <div class="cards">
        <% if @articles.empty? %>
          Pas d'articles trouvés.
        <% else %>
          <% @articles.each do |article| %>
            <%= button_to article_path(article), class: "card-link mb-4", method: :get do %>
              <div class="article-card">
                <div class="article-card-text">
                  <h3 class="text-green text-clamp-1"><%= article.title %></h3>
                  <p><%= article.content %></p>
                </div>
                <%= cl_image_tag article.photo.key, class: "article-card-image" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <%# Display right Panel %>
    <%= render 'shared/right_panel' %>
    <div class="mt-4 pl-2">
      <%= paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container-lg">
  <div class="row adjusted-padding">
    <div class="col-12 col-md-8">
      <div class="mb-3">
        <%= link_to '< Retour à la liste des articles', articles_path, class: "admin-back-link" %>
      </div>
      <div class="d-flex flex-column align-items-center">
          <%= cl_image_tag @article.photo.key, style: "max-width: 80%; max-height: 400px;", class: "mb-4" %>

          <h1 class="text-green mb-4"><%= @article.title %></h1>
          <p class="primary-bold mb-4">Publié le : <%= @article.created_at.strftime("%d/%m/%Y") %></p>

          <p><%= @article.content %></p>
      </div>
    </div>

    <%# Display right Panel %>
    <%= render 'shared/right_panel' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-180944020-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-180944020-1');
    </script>

    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/messages/new.html.erb
<div class="container-lg">
  <div class="row adjusted-padding">
    <div class="col-12 col-md-8">
      <h1 class="text-green mb-4">Contactez-nous</h1>
      <%= simple_form_for @message, url: create_message_url do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs p-2">
          <%= f.input :first_name,
            placeholder: 'Prénom',
            label: 'Votre prénom :',
            required: true,
            error: 'Le prénom est obligatoire'
          %>
          <%= f.input :last_name,
            placeholder: 'Nom',
            label: 'Votre nom :',
            required: true,
            error: 'Le nom est obligatoire'
          %>
          <%= f.input :email,
            placeholder: 'Email',
            label: 'Votre email :',
            required: true,
            error: 'L\'email est obligatoire'
          %>
          <%= f.input :subject,
            placeholder: 'Sujet',
            label: 'Le sujet de votre message :',
            required: true,
            error: 'Le sujet ne peut être vide'
          %>
          <%= f.input :body,
            placeholder: 'Contenu de votre message',
            as: :text,
            label: 'Votre message :',
            required: true,
            error: 'Le message ne peut pas être vide',
            html: { class: "input_body"}
          %>
          </div>

        <div class="form-actions d-flex w-100 justify-content-center mb-4">
          <%= f.button :submit, "Envoyer mon message", class: "btn btn-primary", style: "width: auto" %>
        </div>
      <% end %>
    </div>

    <%# Display right Panel %>
    <%= render 'shared/right_panel' %>
  </div>
</div>

app/views/pages/admin.html.erb
<div class="container-lg min-height-calc adjusted-padding">

  <h1 class="text-green text-center my-4">Salut à toi jeune entrepreneur !</h1>

  <h4 class="text-center my-2">Plus tard, des choix s'offriront à toi, mais pour le moment tu ne peux manager qu'une chose : </h4>
  <h4 class="text-center my-2">Les articles.</h4>

  <div class="w-100 d-flex justify-content-center mt-4">
    <%= link_to 'Manager les articles', admin_articles_path, class: "btn btn-primary"%>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1 class="text-center text-white">Le sport, autrement.</h1>
    <h2 class="text-center text-white">
      Faire du sport, avec du matériel performant, tout en réduisant notre impact environnemental.
      <br>
      C'est notre engagement.
    </h2>
  </div>
</div>

<div class="container-lg mt-4">

  <div class="row">
    <%# Display cards %>
    <div class="col-12 col-md-8">
      <h1 class="text-green mb-4">Nos derniers articles</h1>

      <div class="home-cards pt-4">
        <% @articles.each do |article| %>
          <%= button_to article_path(article), class: "card-link mb-4", method: :get do %>
            <div class="home-card">
              <div class="home-card-text">
                <h3 class="text-clamp-2 text-green text-left"><%= article.title %></h3>
                <p><%= article.content %></p>
              </div>
              <%= cl_image_tag article.photo.key, class: "home-card-image" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <%# Display right Panel %>
    <%= render 'shared/right_panel' %>
  </div>
</div>

<%# Display Instagram pictures %>
<div class="insta-container d-none">
  <div class="container py-4">
    <h1 class="text-green mb-4">SoroSoro sur Instagram</h1>
    <div class="row justify-content-around">
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
      <div class="col-6 col-md-4 col-lg-2 d-flex justify-content-center">
        <div class="fake-photo"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-4">
  <div class="container footer-content">
    <div class="footer-links my-4">
      <%#= link_to 'Mentions Légales', new_message_path %>
      <%#= <br> %>
      <%#= link_to 'Cookies', new_message_path %>
      <%#= <br> %>
      <%= link_to 'Contact', new_message_path %>
    </div>

    <div class="footer-infos">
      <div class="footer-contact mx-4">
        <p class="text-center">contact@sorosoro.net</p>
        <p class="text-center">Tel: 06-00-11-22-33</p>
        <div class="social-medias-footer text-center">
          <a href="https://www.facebook.com/sportresponsable-112477027155896" target="_blank">
            <%= inline_svg_tag('facebook.svg') %>
          </a>
          <a href="https://www.instagram.com/sportresponsable/" target="_blank">
            <%= inline_svg_tag('instagram.svg') %>
          </a>
          <div class="d-none">
            <%= inline_svg_tag('twitter.svg') %>
          </div>
        </div>
      </div>
      <div class="footer-address">
        <h4>SoroSoro Inc.</h4>
        <p>8, cours de la Martinique</p>
        <p>33000 Bordeaux</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-soro">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1 class="text-orange">SoroSoro</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= "active" if request.fullpath == '/' %>">
        <%= link_to "Accueil", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= "active" if request.fullpath.include?('/articles') %>">
        <%= link_to "Blog", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= "active" if request.fullpath == '/valeurs' %>">
        <%= link_to "Valeurs", valeurs_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= "active" if request.fullpath == '/contact' %>">
        <%= link_to "Contact", new_message_path, class: "nav-link" %>
      </li>
      <% if current_user %>
      <li class="nav-item">
          <%= link_to "Admin", admin_path, class: "nav-link logout-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link logout-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_right_panel.html.erb
<div class="col-12 col-md-4">
  <div class="right-panel">

    <%= form_tag articles_path, method: :get, class: "d-none d-md-flex mb-4", id: "search-form" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "right-panel-input",
        placeholder: "Trouver un article"
      %>
      <%= button_tag(type: "submit", class: "btn btn-primary d-flex align-items-center") do %>
        <%= image_tag "loupe.png", width: '20px' %>
      <% end %>
    <% end %>

    <div class="d-none d-md-block last-article">
      <% article = Article.where(displayed: true).last  %>
      <%= link_to article_path(article), class: "card-link" do %>
        <h4 class="text-green text-clamp-1 text-left"><%= article.title %></h4>
        <p>
          <%= article.content %>
        </p>
      <% end %>
    </div>

    <div class="newsletter my-0 my-sm-4">
      <h3 class="text-center text-green my-4">Lettre d'information</h3>
      <%= simple_form_for Contact.new, html: {  class: "d-flex mb-4", id: "newsletter-form" } do |f| %>
        <%= f.input :email, label: false, placeholder: "Votre adresse email", input_html: { class: "right-panel-input" } %>
        <%= f.submit "S'inscrire", class: "btn btn-primary" %>
      <% end %>
    </div>

    <div class="social-medias text-center">
      <a href="https://www.facebook.com/sportresponsable-112477027155896" target="_blank">
        <%= inline_svg_tag('facebook.svg') %>
      </a>
      <a href="https://www.instagram.com/sportresponsable/" target="_blank">
        <%= inline_svg_tag('instagram.svg') %>
      </a>
      <div class="d-none">
        <%= inline_svg_tag('twitter.svg') %>
      </div>
    </div>
  </div>
</div>

app/views/youtubes/_thumbnail.html.erb
<div>
  <%= image_tag youtube.thumbnail_url, style: "max-width:400px" %>
</div>

app/views/youtubes/_youtube.html.erb
<div>
  <iframe id="ytplayer" type="text/html" width="640" height="360" src="https://www.youtube.com/embed/<%= youtube.id %>" frameborder="0"></iframe>
</div>